In [1]:
import os
os.chdir("../../")#与easymlops同级目录

### 拆分数据

In [2]:
import pandas as pd
data=pd.read_csv("./data/demo.csv")
data["date1"]="2020-03-06"
data["date2"]="2023-01-04"
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,date1,date2
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2020-03-06,2023-01-04
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2020-03-06,2023-01-04
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2020-03-06,2023-01-04
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2020-03-06,2023-01-04
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2020-03-06,2023-01-04

In [3]:
x_train=data[:500]
x_test=data[500:]
y_train=x_train["Survived"]
y_test=x_test["Survived"]
del x_train["Survived"]
del x_test["Survived"]

### pipe构建

In [4]:
from easymlops import TablePipeLine

In [5]:
from easymlops.table.preprocessing import *
from easymlops.table.ensemble import Parallel
table=TablePipeLine()
table.pipe(FixInput())\
  .pipe(Parallel([IsNull(),IsNotNull()]))\
  .pipe(FillNa(cols=["Cabin","Ticket","Parch","Fare","Sex"],fill_mode="mode"))\
  .pipe(FillNa(cols=["Age"],fill_mode="mean"))\
  .pipe(FillNa(fill_detail={"Embarked":"N"}))\
  .pipe(FillNa())\
  .pipe(TransToCategory(cols=["Cabin","Embarked","Name"]))\
  .pipe(TransToFloat(cols=["Age","Fare"]))\
  .pipe(TransToInt(cols=["Pclass","PassengerId","SibSp","Parch"]))\
  .pipe(ClipString(cols=["Name"],default_clip_index=(0,10)))\
  .pipe(Replace(cols=["Cabin"],source_values=["nan","N","B79"],target_value="nan"))\
  .pipe(TransToLower(cols=["Ticket","Cabin","Embarked","Name","Sex"]))\
  .pipe(MapValues(map_detail={"Cabin":[(["nan","NaN"],"n")],"Age":[("(-1,10)",10),("[10,20]",20)]}))\
  .pipe(Clip(cols=["Age"],default_clip=(1,99),name="clip_name"))\
  .pipe(Clip(cols=["Fare"],percent_range=(1,99),name="clip_fare"))\
  .pipe(MinMaxScaler(cols=[("Age","Age_minmax")]))\
  .pipe(Normalizer(cols=[("Fare","Fare_normal")]))\
  .pipe(Bins(n_bins=10,strategy="uniform",cols=[("Age","Age_uni")]))\
  .pipe(Bins(n_bins=10,strategy="quantile",cols=[("Age","Age_quan")]))\
  .pipe(Bins(n_bins=10,strategy="kmeans",cols=[("Fare","Fare_km")]))\
  .pipe(Parallel([Add(left_col_name="Pclass",right_col_name="SibSp"),
                  Subtract(left_col_name="Pclass",right_col_name="Fare"),
                  Multiply(left_col_name="Fare",right_col_name="Age"),
                  Divide(left_col_name="Age_minmax",right_col_name="Fare_normal"),
                  DivideExact(left_col_name="Age_minmax",right_col_name="Pclass"),
                  Mod(left_col_name="PassengerId",right_col_name="Pclass")]))\
  .pipe(Parallel([Equal(left_col_name="Pclass",right_col_name="SibSp"),
                  GreaterThan(left_col_name="Pclass",right_col_name="Fare"),
                  GreaterEqualThan(left_col_name="Fare",right_col_name="Age"),
                  LessThan(left_col_name="Age_minmax",right_col_name="Fare_normal"),
                  LessEqualThan(left_col_name="Age_minmax",right_col_name="Pclass"),
                  And(left_col_name="PassengerId",right_col_name="Pclass"),
                  Or(left_col_name="Pclass",right_col_name="SibSp")]))\
  .pipe(DateDayDiff(left_col_name="date2",right_col_name="date1"))


x_test_new=table.fit(x_train).transform(x_test)
x_test_new.head(5)

,Pclass_equal_SibSp,Pclass_greater_than_Fare,Fare_greater_equal_than_Age,Age_minmax_less_than_Fare_normal,Age_minmax_less_equal_than_Pclass,PassengerId_and_Pclass,Pclass_add_SibSp,Pclass_subtract_Fare,Fare_multiply_Age,Age_minmax_divide_Fare_normal,...,date1_is_not_null,date2_is_not_null,Age_minmax,Fare_normal,Age_uni,Age_quan,Fare_km,PassengerId_mod_Pclass,Pclass_or_SibSp,date2_day_diff_date1
500,0,0,0,0,1,1,3,-5.664062,173.281250,-0.307692,...,1,1,0.16,-0.52,1,1,1,0,1,1034
501,0,0,0,0,1,1,3,-4.750000,162.750000,-0.333333,...,1,1,0.18,-0.54,1,2,1,1,1,1034
502,0,0,0,0,1,1,3,-4.628906,222.787903,-0.574074,...,1,1,0.31,-0.54,3,5,1,2,1,1034
503,0,0,0,0,1,1,3,-6.585938,354.679688,-0.880000,...,1,1,0.44,-0.50,4,6,1,0,1,1034
504,0,0,1,1,1,1,1,-85.500000,1730.000000,0.125984,...,1,1,0.16,1.27,1,1,4,0,1,1034

### 性能、一致性测试

In [ ]:
table.auto_test(x_test[:5])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.4ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.2ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.TransToCategory'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.TransToFloat'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.TransToInt'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.ClipString'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.Replace'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.TransToLower'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.MapValues'>) module check [transform] complete,speed:[0.2ms]/it,cpu:[0%],memory:[0K]
(clip_name) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(clip_fare) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.MinMaxScaler'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.Normalizer'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.Bins'>) module check [transform] complete,speed:[6.21ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.Bins'>) module check [transform] complete,speed:[5.42ms]/it,cpu:[37%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.Bins'>) module check [transform] complete,speed:[5.62ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[0.4ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.ensemble.Parallel'>) module check [transform] complete,speed:[0.6ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.bivar_operation.DateDayDiff'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[19.82ms]/it,cpu:[44%],memory:[0K]
column:[Pclass] check [null value] complete,speed:[21.37ms]/it,cpu:[47%],memory:[320K]
column:[Name] check [null value] complete,speed:[21.26ms]/it,cpu:[36%],memory:[64K]
column:[Sex] check [null value] complete,speed:[22.69ms]/it,cpu:[49%],memory:[4K]
column:[Age] check [null value] complete,speed:[21.98ms]/it,cpu:[48%],memory:[200K]
column:[SibSp] check [null value] complete,speed:[22.67ms]/it,cpu:[43%],memory:[872K]
column:[Parch] check [null value] complete,speed:[21.84ms]/it,cpu:[41%],memory:[44K]
column:[Ticket] check [null value] complete,speed:[22.05ms]/it,cpu:[42%],memory:[32K]
column:[Fare] check [null value] complete,speed:[22.03ms]/it,cpu:[40%],memory:[3312K]
column:[Cabin] check [null value] complete,speed:[21.96ms]/it,cpu:[48%],memory:[532K]
column:[Embarked] check [null value] complete,speed:[22.69ms]/it,cpu:[53%],memory:[5300K]
column:[date1] check [null value] complete,speed:[23.47ms]/it,cpu:[41%],memory:[0K]
column:[date2] check [null value] complete,speed:[22.06ms]/it,cpu:[44%],memory:[16K]

############################################################################################################
 3.极端值测试:check_extreme_value
 number_extreme_values = [np.inf, 0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 category_extreme_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1", "NaN", "None"](默认)
###########################################################################################################
column:[PassengerId] check [extreme value] complete,speed:[22.43ms]/it,cpu:[58%],memory:[16532K]
column:[Pclass] check [extreme value] complete,speed:[22.26ms]/it,cpu:[74%],memory:[29544K]
column:[Name] check [extreme value] complete,speed:[21.71ms]/it,cpu:[59%],memory:[31208K]
column:[Sex] check [extreme value] complete,speed:[22.34ms]/it,cpu:[60%],memory:[32288K]
column:[Age] check [extreme value] complete,speed:[22.22ms]/it,cpu:[78%],memory:[12168K]
column:[SibSp] check [extreme value] complete,speed:[21.51ms]/it,cpu:[55%],memory:[90228K]
column:[Parch] check [extreme value] complete,speed:[25.83ms]/it,cpu:[93%],memory:[239548K]
column:[Ticket] check [extreme value] complete,speed:[29.07ms]/it,cpu:[97%],memory:[351772K]
column:[Fare] check [extreme value] complete,speed:[21.04ms]/it,cpu:[49%],memory:[15576K]
column:[Cabin] check [extreme value] complete,speed:[19.78ms]/it,cpu:[48%],memory:[12296K]
column:[Embarked] check [extreme value] complete,speed:[21.56ms]/it,cpu:[63%],memory:[60924K]
column:[date1] check [extreme value] complete,speed:[21.08ms]/it,cpu:[68%],memory:[8384K]
column:[date2] check [extreme value] complete,speed:[24.04ms]/it,cpu:[62%],memory:[6988K]
column:[__all__] check [extreme value] complete,speed:[22.65ms]/it,cpu:[76%],memory:[607332K]

###############################################################################################################
 4.数据类型反转测试:check_inverse_dtype
 category_inverse_values = [0.0, -1, 1, -1e-7, 1e-7, np.finfo(np.float64).min, np.finfo(np.float64).max](默认)
 number_inverse_values = ["", "null", None, "1.0", "0.0", "-1.0", "-1"](默认)
#############################################################################################################
column:[PassengerId] check [inverse type] complete,speed:[24.35ms]/it,cpu:[71%],memory:[100468K]
column:[Pclass] check [inverse type] complete,speed:[22.5ms]/it,cpu:[73%],memory:[92936K]
column:[Name] check [inverse type] complete,speed:[20.99ms]/it,cpu:[53%],memory:[14164K]
column:[Sex] check [inverse type] complete,speed:[21.79ms]/it,cpu:[71%],memory:[6844K]
column:[Age] check [inverse type] complete,speed:[24.28ms]/it,cpu:[67%],memory:[28716K]
column:[SibSp] check [inverse type] complete,speed:[23.07ms]/it,cpu:[49%],memory:[82056K]
column:[Parch] check [inverse type] complete,speed:[22.41ms]/it,cpu:[53%],memory:[89320K]
column:[Ticket] check [inverse type] complete,speed:[24.51ms]/it,cpu:[98%],memory:[153816K]
column:[Fare] check [inverse type] complete,speed:[25.45ms]/it,cpu:[72%],memory:[100828K]
column:[Cabin] check [inverse type] complete,speed:[22.02ms]/it,cpu:[62%],memory:[40064K]
column:[Embarked] check [inverse type] complete,speed:[21.71ms]/it,cpu:[68%],memory:[340016K]
column:[date1] check [inverse type] complete,speed:[19.75ms]/it,cpu:[35%],memory:[1716K]

### 持久化测试

In [ ]:
table.save("ml.pkl")

In [ ]:
table=TablePipeLine()
table.pipe(FixInput())\
  .pipe(Parallel([IsNull(),IsNotNull()]))\
  .pipe(FillNa(cols=["Cabin","Ticket","Parch","Fare","Sex"],fill_mode="mode"))\
  .pipe(FillNa(cols=["Age"],fill_mode="mean"))\
  .pipe(FillNa(fill_detail={"Embarked":"N"}))\
  .pipe(FillNa())\
  .pipe(TransToCategory(cols=["Cabin","Embarked","Name"]))\
  .pipe(TransToFloat(cols=["Age","Fare"]))\
  .pipe(TransToInt(cols=["Pclass","PassengerId","SibSp","Parch"]))\
  .pipe(ClipString(cols=["Name"],default_clip_index=(0,10)))\
  .pipe(Replace(cols=["Cabin"],source_values=["nan","N","B79"],target_value="nan"))\
  .pipe(TransToLower(cols=["Ticket","Cabin","Embarked","Name","Sex"]))\
  .pipe(MapValues(map_detail={"Cabin":[(["nan","NaN"],"n")],"Age":[("(-1,10)",10),("[10,20]",20)]}))\
  .pipe(Clip(cols=["Age"],default_clip=(1,99),name="clip_name"))\
  .pipe(Clip(cols=["Fare"],percent_range=(1,99),name="clip_fare"))\
  .pipe(MinMaxScaler(cols=[("Age","Age_minmax")]))\
  .pipe(Normalizer(cols=[("Fare","Fare_normal")]))\
  .pipe(Bins(n_bins=10,strategy="uniform",cols=[("Age","Age_uni")]))\
  .pipe(Bins(n_bins=10,strategy="quantile",cols=[("Age","Age_quan")]))\
  .pipe(Bins(n_bins=10,strategy="kmeans",cols=[("Fare","Fare_km")]))\
  .pipe(Parallel([Add(left_col_name="Pclass",right_col_name="SibSp"),
                  Subtract(left_col_name="Pclass",right_col_name="Fare"),
                  Multiply(left_col_name="Fare",right_col_name="Age"),
                  Divide(left_col_name="Age_minmax",right_col_name="Fare_normal"),
                  DivideExact(left_col_name="Age_minmax",right_col_name="Pclass"),
                  Mod(left_col_name="PassengerId",right_col_name="Pclass")]))\
  .pipe(Parallel([Equal(left_col_name="Pclass",right_col_name="SibSp"),
                  GreaterThan(left_col_name="Pclass",right_col_name="Fare"),
                  GreaterEqualThan(left_col_name="Fare",right_col_name="Age"),
                  LessThan(left_col_name="Age_minmax",right_col_name="Fare_normal"),
                  LessEqualThan(left_col_name="Age_minmax",right_col_name="Pclass"),
                  And(left_col_name="PassengerId",right_col_name="Pclass"),
                  Or(left_col_name="Pclass",right_col_name="SibSp")]))\
  .pipe(DateDayDiff(left_col_name="date2",right_col_name="date1"))

table.load("ml.pkl")

In [ ]:
table.auto_test(x_test[:10])

In [ ]:
table.transform(x_test[:5])

In [ ]:
x_test_new.head(5)