In [1]:
import os
os.chdir("../../")#与easymlops同级目录

### 拆分数据

In [2]:
import pandas as pd
data=pd.read_csv("./data/demo.csv")
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
x_train=data[:500]
x_test=data[500:]
y_train=x_train["Survived"]
y_test=x_test["Survived"]
del x_train["Survived"]
del x_test["Survived"]

### pipe构建

In [4]:
from easymlops import NLPPipeline
from easymlops.table.preprocessing import *
from easymlops.table.encoding import *
from easymlops.nlp.preprocessing import *
from easymlops.nlp.representation import *
from easymlops.table.perfopt import *

In [5]:
nlp=NLPPipeline()
nlp.pipe(FixInput())\
   .pipe(FillNa())\
   .pipe(SelectCols(cols=["Name","Age"]))\
   .pipe(Lower(cols=["Name"]))\
   .pipe(RemovePunctuation(cols=["Name"]))\
   .pipe(TFIDF(cols=["Name"]))\

x_test_new=nlp.fit(x_train).transform(x_test)
x_test_new.head(5)

,tfidf_Name_,tfidf_Name_a,tfidf_Name_abbott,tfidf_Name_abelson,tfidf_Name_achem,tfidf_Name_achille,tfidf_Name_achilles,tfidf_Name_ada,tfidf_Name_adahl,tfidf_Name_adams,...,tfidf_Name_y,tfidf_Name_yoto,tfidf_Name_young,tfidf_Name_youseff,tfidf_Name_yousif,tfidf_Name_youssef,tfidf_Name_yousseff,tfidf_Name_yrois,tfidf_Name_zabour,tfidf_Name_zimmerman
500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
502,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
503,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
504,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
x_test_new.memory_usage().sum()//1024

11

### 性能、一致性测试

In [ ]:
nlp.auto_test(x_test[:10])

###################################################################
 1.一致性测试和性能测试:check_transform_function
###################################################################
(<class 'easymlops.table.preprocessing.core.FixInput'>) module check [transform] complete,speed:[0.3ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.onevar_operation.FillNa'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.table.preprocessing.core.SelectCols'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.Lower'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.preprocessing.RemovePunctuation'>) module check [transform] complete,speed:[0.0ms]/it,cpu:[0%],memory:[0K]
(<class 'easymlops.nlp.representation.TFIDF'>) module check [transform] complete,speed:[320.46ms]/it,cpu:[56%],memory:[17328K]

#########################################################################################
 2.空值测试:check_null_value
 null_values=[None, np.nan, "null", "NULL", "nan", "NaN", "", "none", "None", " "](默认)
########################################################################################
column:[PassengerId] check [null value] complete,speed:[324.87ms]/it,cpu:[55%],memory:[85484K]
column:[Pclass] check [null value] complete,speed:[341.38ms]/it,cpu:[49%],memory:[12784K]
column:[Name] check [null value] complete,speed:[341.28ms]/it,cpu:[55%],memory:[26280K]

### 持久化测试

In [ ]:
nlp.save("ml.pkl")

In [ ]:
nlp=NLPPipeline()
nlp.pipe(FixInput())\
   .pipe(FillNa())\
   .pipe(SelectCols(cols=["Name","Age"]))\
   .pipe(Lower(cols=["Name"]))\
   .pipe(RemovePunctuation(cols=["Name"]))\
   .pipe(TFIDF(cols=["Name"]))\

nlp.load("ml.pkl")

In [ ]:
nlp.auto_test(x_test[:10])

In [ ]:
nlp.transform(x_test[:5])

In [ ]:
x_test_new.head(5)